wordpress:
    image: wordpress:4.9
    links:
        - mariadb:mysql
    environment:
        - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
    ports:
        - "80:80"
    volumes:
        - ./code:/code
        - ./www:/var/www/html
mariadb:
    image: mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DB_NAME}
    volumes:
        - ./docker/mysql/dump:/docker-entrypoint-initdb.d
